### ISSUE TITLE
How to add floating button?

### ISSUE THREAD

**Issue by Faiyyaz** [drogel/keyboard_attachable#11]
Hey thanks for the library.

But i want to use a floating button with this library but unable to do so. Can you guide me?

**Comment by drogel** [comment]
Hi, thank you for using it and contributing to it!

Depends a lot on what you are trying to implement exactly. As you suggested, I implemented a transition builder example that makes use of the transition to present an icon button with an animation that matches the soft keyboard animation. You can find the example in the project. 

Take a look at it and see if it helps (if you haven't already). If the example has nothing to do with what you want to implement, please provide more details about what you are trying to implement exactly, and I will try to reproduce it using the library.

**Comment by Faiyyaz** [comment]
It sort of same but not much... But i had done the required thing using stack and positioned.fill. Thanks for the help though :)

**Comment by drogel** [comment]
No problem! Happy to read that you managed to implement it!
