### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by maximletushov** [drogel/keyboard_attachable#15]
I was wondering if there is already a roadmap for migrating this library to null safety?
https://dart.dev/null-safety/migration-guide

**Comment by drogel** [comment]
Hi @maximletushov, thanks for bringing this issue to my attention.

Right now there is no defined roadmap for null safety migration, but that does not mean that I am not planning on migrating the package to null safety at some point.

This package is fairly simple, so it should not be very hard to do it. The only difficulty I see is that this package depends on another package (`flutter_keyboard_visibility`), and I'm not sure if that package has been migrated yet.

**Comment by maximletushov** [comment]
@drogel thank you for great package and your support !
I opened the same issue in `flutter_keyboard_visibility` https://github.com/MisterJimson/flutter_keyboard_visibility/issues/49

**Comment by drogel** [comment]
Perfect, I will keep an eye on it. Thanks a lot!

**Comment by maximletushov** [comment]
Hi @drogel 
Null safety is released in Dart 2.12 https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87
Please take a look.

**Comment by drogel** [comment]
Hi @maximletushov & @Jjagg,

Just writing to let you know that a null-safety compatible version of `keyboard_attachable` has been just released. Checkout out

https://pub.dev/packages/keyboard_attachable

for the 2.0.0 version! 🎉 

Thanks @Jjagg for your help with the migration, and @maximletushov for being up-to-date with Dart null safe releases.
