### ISSUE TITLE
Update flutter_keyboard_visibility to 5.4.1

### ISSUE THREAD

**Issue by guyluz11** [drogel/keyboard_attachable#29]
Current [flutter_keyboard_visibility](https://pub.dev/packages/flutter_keyboard_visibility) is `5.0.0`

I can see that there are some good changes when moving to `5.4.1` like
* "Replaced jcenter with mavenCentral"
* "Removed Android v1 Embedding Support."
* "
    Updated Android target/compile SDK versions to 30
    Updated Android gradle build tools to 3.6.4
    Updated AndroidX Core to 1.5.0-rc01
"

**Comment by drogel** [comment]
A release 2.2.0 has been created to address this issue, thanks to @ryanaidilp! 🎉
